**00 PyTorch Fundamnentals**

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

scalar = torch.tensor(7)
scalar


tensor(7)

**Introduction to Tensors**

Creating tensors

PyTorch tensors are created using 'torch.tensor()'

https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()


7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[[1, 2, 3],
                        [3, 7, 12],
                        [2,4,5],
                        [34,56,10]]]])
TENSOR

tensor([[[[ 1,  2,  3],
          [ 3,  7, 12],
          [ 2,  4,  5],
          [34, 56, 10]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

**Random tensors**

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update randon numbers -> look at data  -> update random numbers`

Torch random tensors  https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor





tensor([[0.4741, 0.7320, 0.6622, 0.5018],
        [0.3607, 0.6941, 0.1484, 0.6258],
        [0.5299, 0.5810, 0.6519, 0.2101]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

**Zeros and ones**

In [ ]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
ones*random_tensor

tensor([[0.4741, 0.7320, 0.6622, 0.5018],
        [0.3607, 0.6941, 0.1484, 0.6258],
        [0.5299, 0.5810, 0.6519, 0.2101]])

**Creating a range of tensore and tensors-like**


In [ ]:
# Use torch.range() and get deprecated message use torch.arrange()
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one = torch.arange(start=0, end=1000, step=78)
one

tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])

In [ ]:
# Create a tensor-like
two = torch.zeros_like(input=one)
two

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**

**Note** Tensor datatypes is one of the three big errors you'll run into  with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computer science
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) #whether or not to track gradience with this tensor operations
float_32_tensor



tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

**Getting information from tensors** (tensors attrbutes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor. dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.9764, 0.4311, 0.0145, 0.4769],
        [0.7063, 0.9313, 0.6368, 0.8989],
        [0.1881, 0.0015, 0.1331, 0.2131]])

In [ ]:
# Find out detailes about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")  #tensor.size do the same as tensor.shape {tensor.size is a function}
print(f"Device tensor is on: {some_tensor.device}")



tensor([[0.9764, 0.4311, 0.0145, 0.4769],
        [0.7063, 0.9313, 0.6368, 0.8989],
        [0.1881, 0.0015, 0.1331, 0.2131]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manupulating Tensors (tensor operations)

Tensor operations include:

*Addition

*Subtraction

*Multiplication (element-wise)

*Division

*Matrix multiplication https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by ten
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

**Matrix multiplication**

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product) https://en.wikipedia.org/wiki/Dot_product

More info about multiplying  matrices https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy

1. The **inner dimensions** must match:
* ~(3,2) @ (3, 2) won't work
* ~(2, 3) @ (3,2) will work
* ~(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimensions**:
*~(2,3) @ (3,2) -> ~(2,2)`

*~(2,3) @ (3,2) -> ~(3,3)`


In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2, 3))

tensor([[0.8325, 0.9440, 0.1612],
        [0.8740, 0.9426, 0.1322],
        [0.6277, 0.7339, 0.1385]])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplictaion
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.98 ms, sys: 0 ns, total: 2.98 ms
Wall time: 2.68 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 514 µs, sys: 0 ns, total: 514 µs
Wall time: 376 µs


tensor(14)

One of the most common errors in deep learning: shape errors

http://matrixmultiplication.xyz/


In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5,6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.matmul(tensor_A, tensor_B) # or torch.mm instead of torch.matmul (it's for writing less code)



RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


**Finding the min, max, mean, sum, etc(tensor aggregation)**

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()


(tensor(91), tensor(91))

In [ ]:
#Find the mean - note: the torch.mean() function reqires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

**Find the poitional min and max**

In [ ]:

x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin(), x.argmax()


(tensor(0), tensor(9))

In [ ]:
x[0], x[9]

(tensor(1), tensor(91))

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

**Reshaping, stacking, squeezing and unsqeezing tensors**

* Reshaping - reshapes an input tensor to a defined shaped

* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine mltiple tensors on top of each other (vstack - vertical stack) or side by side (hstack - horizontal stack)
* Squeeze - removes all `1` dimensions from a tensor

* Unsqueeze - add a `1` dimension to a target tensor

* Permute - return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Chahging z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension  with unsqeeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [ ]:
# torche.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, weight, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shift axis 0->1, 1->2, 2->0
x_permuted.shape # [colour_channels, height, weight]


torch.Size([3, 224, 224])

In [ ]:
x_original[0, 0, 0] = 378623
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(378623.), tensor(378623.))

**Indexing (selecting data from tensors)**

Indexing with Pytorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape



(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)

x[0][2][2]


tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of second dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1st index value of 1st and 2nd dimensions
x[0, 1, 1]

tensor(5)

In [ ]:
# Get index 0  of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]


tensor([1, 2, 3])

In [ ]:
#Index on x to return 9
x[0][2][2]

#Index on x to return 3,6,
x[:, :, 2]

tensor([[3, 6, 9]])

**PyTorch tensors and NumPy**

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact this it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility (trying to take random out of random)**

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch  comes the concept of a **random seed**.

What the random seed does is "flavour" the randomness.

In [18]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9951, 0.2214, 0.8595, 0.3695],
        [0.7255, 0.4421, 0.9159, 0.4740],
        [0.8625, 0.2077, 0.8914, 0.4350]])
tensor([[0.5373, 0.8676, 0.1334, 0.4318],
        [0.5276, 0.0322, 0.4633, 0.6052],
        [0.0036, 0.4167, 0.2956, 0.7260]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
